name = "backend"
compatibility_date = "2024-09-08"
# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYmE0MDNiOWMtZGFiNy00YTA4LWI3MzgtNjM2MDI2ZGI4NWQ2IiwidGVuYW50X2lkIjoiZjBlNzI4ZjY5ZjVhNzhjOGZjNzIyMWVhYTkzODk5NDM3OTI1NmY3MGVjNGEwMjcxYzkxNWU2ZjBmMjg5YmYwMSIsImludGVybmFsX3NlY3JldCI6IjFhZTM0NjBlLWM0NjQtNDk3NS05MzYwLTIxZGQyYzE2ZjMyNSJ9.FeErsp95PWW2E-b7-LvsBGxjoP9SdskMhKjV5oN-he8"

JWT_SECRET="The_secret_key"

